fixing -> 323 create_pacf_features(top_features)     324 create_acf_features(top_features)     325 create_autocorr_features(top_features)
Cell In[128], line 122
    120 shifted_col = df[c].shift(shift_periods).fillna(0.0)
    121 # Change from 'ywunbiased' to 'yw' (Yule-Walker method)
...
   1054     )
   1055 if method in ("ols", "ols-inefficient", "ols-adjusted"):
   1056     efficient = "inefficient" not in method

ValueError: Can only compute partial correlations for lags up to 50% of the sample size. The requested nlags 10 must be < 5.
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...