to fix    1521 @functools.wraps(func)    1522 def inner(ax, *args, data=None, **kwargs):    1523     if data is None: -> 1524         return func(    1525             ax,    1526             *map(cbook.sanitize_sequence, args), ...     318             f"autodetected range of [{first_edge}, {last_edge}] is not finite")     320 # expand empty range to avoid divide by zero     321 if first_edge == last_edge:
ValueError: autodetected range of [nan, nan] is not finite